# Generated by Django 2.0.4 on 2018-09-20 05:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_30', models.IntegerField(default=0)),
                ('score_20', models.IntegerField(default=0)),
                ('score_10', models.IntegerField(default=0)),
                ('score_10p', models.IntegerField(default=0)),
                ('score_20p', models.IntegerField(default=0)),
                ('score_30p', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=' ', max_length=150)),
                ('answer', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=1)),
                ('ans1', models.IntegerField(default=None)),
                ('ans2', models.IntegerField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('timer', models.TimeField(default='00:00')),
                ('email_1', models.EmailField(default='player_1@gmail.com', max_length=20, validators=[django.core.validators.EmailValidator()])),
                ('email_2', models.EmailField(default='player_2@gmail.com', max_length=20, validators=[django.core.validators.EmailValidator()])),
                ('name_1', models.CharField(default='player_1', max_length=20)),
                ('name_2', models.CharField(default='player_2', max_length=20)),
                ('number_1', models.IntegerField(default=0)),
                ('number_2', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('no_question', models.IntegerField(default=0)),
                ('attempt_question', models.IntegerField(default=0)),
                ('add_time', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
