# Generated by Django 2.0.4 on 2018-09-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
    ]
