# Generated by Django 2.0.4 on 2018-09-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='ans1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='ans2',
            field=models.IntegerField(null=True),
        ),
    ]
