# Generated by Django 2.0.4 on 2018-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180912_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.IntegerField(default=0),
        ),
    ]
