# Generated by Django 2.1.1 on 2018-09-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userprofile_add_time'),
        ('app1', '0002_auto_20180920_0549'),
    ]

    operations = [
    ]
